#!/bin/bash
ARG=$@

#color
_RED="\033[31m"
_GREEN="\033[32m"
_END="\033[0m"

#setup
make
mkdir ../tmp

#check function
check () {
	ls -1   $1 >& ../tmp/original_tmp_tmp;
	./ft_ls $1 >& ../tmp/mine_tmp;

	#trim "ls: "
	cat ../tmp/original_tmp_tmp | sed 's/^ls: //' > ../tmp/original_tmp
	#remove padding and ACL
	cat ../tmp/original_tmp | tr -s "\n " | tr -d "@+" > ../tmp/original
	cat ../tmp/mine_tmp | tr -s "\n " | tr -d "@+" > ../tmp/mine

	#check diff
	diff -w ../tmp/original ../tmp/mine > /dev/null;
	if [ $? = 0 ]; then
		printf "\n"
		echo $1
		printf ":${_GREEN}PASS${_END}\n" 2> /dev/null;
	else
		printf "\n"
		echo $1
		printf ":${_RED}FAILURE${_END}\n" 2> /dev/null;
		# rm -rf tmp;
		exit 1;
	fi

	# check memory leak
	if [ "$ARG" = "-m" ]; then
		valgrind ./ft_ls $1 >& ../tmp/leak_tmp
		bytes=`grep definitely ../tmp/leak_tmp | sed 's/.*: \([0-9]*\).*/\1/'`
		test ${bytes} = 0
		if [ $? = 0 ]; then
			printf ":${_GREEN}NO LEAK${_END}\n" 2> /dev/null;
		else
			printf ":${_RED}LEAK DETECTED${_END}\n" 2> /dev/null;
			# rm -rf tmp;
			exit 1;
		fi
	fi
}

do_cases() {
	# may take too much time
	if [ ! `echo $1 | grep R` ]; then
		check "${1} /"
		check "${1} ./../../."
	fi

	check "${1} "
	check "${1} ."
	check "${1} ./././."
	check "${1} test_folder"
	check "${1} test_folder/aaa test_folder/bbb"
	check "${1} Makefile test_folder/aaa"
	check "${1} Makefile Makefile"
	check "${1} Makefile Makefile test_folder/aaa"
	check "${1} test_folder/aaa Makefile"
	check "${1} zzz yyy test_folder/ccc xyz wwww "
	check "${1} wwwwwwwwwwww ww ww   fjeoaj test_folder/aaa"
	check "${1} test_folder/bbb Makefile test_folder/cccw test_folder/ccc test_folder/aaa jeoaj test_folder/aaa"
	check "${1} README.md test_folder/aaa README.md test_folder/aaa test_folder/ccc Makefile"
	check "${1} README.md test_folder/aaa README.md test_folder/aaa ccc Makefile"
}

#case

do_cases ""
do_cases "-R"
do_cases "-a"
do_cases "-t"
do_cases "-r"
do_cases "-l"
do_cases "-Ra"
do_cases "-Rt"
do_cases "-Rr"
do_cases "-Rl"
do_cases "-at"
do_cases "-ar"
do_cases "-al"
do_cases "-tr"
do_cases "-tl"
do_cases "-rl"
do_cases "-Rat"
do_cases "-Rar"
do_cases "-Ral"
do_cases "-Rtr"
do_cases "-Rtl"
do_cases "-Rrl"
do_cases "-atr"
do_cases "-atl"
do_cases "-arl"
do_cases "-trl"
do_cases "-Ratr"
do_cases "-Ratl"
do_cases "-Rarl"
do_cases "-Rtrl"
do_cases "-atrl"
do_cases "-Ratrl"

#teardown
# rm -rf ../tmp leak_tmp;
printf "${_GREEN}SUCCESS ${_END} \n"
